import sqlite3
import aiosqlite
import asyncio
import abc
import typing
import psycopg
from loguru import logger

from database.models import Members, Admins, Jury, Group
from sqlalchemy import select, update, delete, and_
from sqlalchemy.dialects.postgresql import insert
from psycopg_pool import ConnectionPool, AsyncConnectionPool
from config import DATABASE_URL


class CrudDatabase(abc.ABC):
    def __init__(self, conn):
        pass

    @staticmethod
    async def add(*args, **kwargs) -> None:
        pass




class DatabasePrepare(abc.ABC):
    @staticmethod
    async def prepare(pool) -> None:
        pass



#=======ADD ON CONFLICT STATMENT
@typing.final
class AdminCRUD(CrudDatabase):
    def __init__(self, conn):
        self.conn = conn

    async def add(self, fio: str, status: str) -> None:
        New_user = Admins(fio=fio, status=status)
       
        stmt = insert(Admins).values(
            fio=fio,
            status=status
        )

        await self.conn.execute(stmt)
        await self.conn.commit()




@typing.final
class MembersCRUD(CrudDatabase):
    @staticmethod
    async def add(session, fio: str, group_name: str, password, email:str, github_link: str) -> None:
        New_user = Members(fio=fio, group_name=group_name, password=password, email=email, github_link=github_link)
       
        stmt = insert(Members).values(
            fio=fio,
            group_name=group_name,
            password=password,
            email=email,
            github_link=github_link
        )

        await session.execute(stmt)
        await session.commit()

    @staticmethod
    async def get(session, email:str, password: str) -> None:
        stmt = select(Members).where(and_(Members.email==email, Members.password==password))
        result = await session.execute(stmt)

        return result.scalar_one_or_none()

class Postgrepool():
    @staticmethod
    def get_pool():
        pool_url = DATABASE_URL.replace("+asyncpg", "")
        pool = AsyncConnectionPool(conninfo=f"{pool_url}?sslmode=disable&gssencmode=disable",
            min_size=4,
            max_size=10
        )
        
        logger.info('Succes connection')

        return pool


#============PASSWORD IN USERS NEDDED===========
#============What we need to add to admin columns in?
#============А собственно как нам хранить оценки за перзу и документацию и прочие?
@typing.final
class PostgrePrepare(DatabasePrepare):
    @staticmethod
    async def prepare(pool) -> None:
        try:
            async with pool.connection() as conn:
                async with conn.cursor() as cur:
                    await cur.execute("""CREATE TABLE IF NOT EXISTS members(
                    db_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    fio VARCHAR(60) NOT NULL,
                    group_name VARCHAR(40) NOT NULL UNIQUE,
                    github_link VARCHAR(100) NOT NULL,
                    email VARCHAR(100) NOT NULL,
                    password VARCHAR(100) NOT NULL)
                    """)


                    await cur.execute("""CREATE TABLE IF NOT EXISTS admin(
                    db_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    fio VARCHAR(60) NOT NULL,
                    group_name VARCHAR(40) NOT NULL UNIQUE
                    )
                    """)

                    await cur.execute("""CREATE TABLE IF NOT EXISTS jury(
                    db_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    fio VARCHAR(60) NOT NULL
                    )
                    """)

                    await cur.execute("""CREATE TABLE IF NOT EXISTS groups(
                    db_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    group_score INT, 
                    group_name VARCHAR(20) UNIQUE
                    )
                    """)
                   
                    await conn.commit()

            logger.info("Tables created")
        except Exception as e:
            logger.exception('Cant create table...', e)
            



