import sqlite3
import aiosqlite
import asyncio
import abc
import typing
import psycopg2
from loguru import logger

from models import Members, Admins, Jury, Group
from sqlalchemy import select, update, delete, and_
from sqlalchemy.dialects.postgresql import insert

class CrudDatabase(abc.ABC):
    def __init__(self, conn):
        pass

    @abc.abstractmethod
    @staticmethod
    async def add(*args, **kwargs) -> None:
        pass


class DatabasePrepare(abc.ABC):
    @abc.abstractmethod
    @staticmethod
    async def prepare(pool) -> None:
        pass


#=======ADD ON CONFLICT STATMENT
@typing.final
class AdminCRUD(CrudDatabase):
    def __init__(self, conn):
        self.conn = conn

    async def add(self, fio: str, status: str) -> None:
        New_user = Admins(fio=fio, status=status)
       
        stmt = insert(Members).values(
            fio=fio,
            status=status
        )

        await self.conn.execute(stmt)
        await self.conn.commit()




@typing.final
class MembersCRUD(CrudDatabase):
    def __init__(self, conn):
        self.conn = conn

    async def add(self, fio: str, group_name: str, github_link: str, present: bytes) -> None:
        New_user = Members(fio=fio, group_name=group_name, github_link=github_link, present=present)
       
        stmt = insert(Members).values(
            fio=fio,
            group_name=group_name,
            github_link=github_link,
            present=present
        )

        await self.conn.execute(stmt)
        await self.conn.commit()




#============PASSWORD IN USERS NEDDED===========
@typing.final
class PostgrePrepare(DatabasePrepare):
    @staticmethod
    async def prepare(pool) -> None:
        try:
            with pool.connection() as conn:
                with conn.cursos() as cur:
                    cur.execute("""CREATE TABLE IF NOT EXISTS members(
                    db_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    fio VARCHAR(60) NOT NULL,
                    group_name VARCHAR(40) NOT NULL UNIQUE,
                    github_link VARCHAR(100) NOT NULL,
                    present BYTEA)
                    """)

                    cur.execute("""CREATE TABLE IF NOT EXISTS admin(
                    db_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    fio VARCHAR(60) NOT NULL,
                    group_name VARCHAR(40) NOT NULL UNIQUE
                    )
                    """)

                    cur.execute("""CREATE TABLE IF NOT EXISTS jury(
                    db_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    fio VARCHAR(60) NOT NULL
                    """)

                    cur.execute("""CREATE TABLE IF NOT EXISTS groups(
                    db_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    group_score INT, 
                    group_name VARCHAR(20) UNIQUE
                    )
                    """)
                   
                    conn.commit()

            logger.info("Tables created")
        except Exception as e:
            logger.exception('Cant create table...', e)
            



